[versions]
# Latest version: https://github.com/FabricMC/fabric-example-mod/blob/1.21/build.gradle
java = "21"

# Latest version: https://github.com/JetBrains/kotlin/releases
kotlin = "2.3.0"

# Latest versions: https://fabricmc.net/develop/
minecraft = "1.21.11"
fabric_loader = "0.18.3"
fabric_loom = "1.14-SNAPSHOT"
fabric_api = "0.140.0+1.21.11"

# Latest version: https://github.com/FabricMC/fabric-language-kotlin/releases
fabric_lang_kotlin = "1.13.8+kotlin.2.3.0"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }
fabric_lang_kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric_lang_kotlin" }

[plugins]
fabric_loom = { id = "fabric-loom", version.ref = "fabric_loom" }
